#/bin/sh
apt-cyg install wget
apt-cyg install curl
apt-cyg install ssh
apt-cyg install nc
apt-cyg install screen
apt-cyg install whois
apt-cyg install libiconv
apt-cyg install zip
apt-cyg install unzip
apt-cyg install vim
apt-cyg install rdiff-backup
apt-cyg install rsync
apt-cyg install git
apt-cyg install tig
apt-cyg install subversion
apt-cyg install bc
apt-cyg install chere
apt-cyg install bash-completion
